# Generated by Django 3.0.5 on 2020-04-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default='sada', max_length=25),
            preserve_default=False,
        ),
    ]
