# Generated by Django 3.0.5 on 2020-04-23 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20200423_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
    ]
