# Generated by Django 3.0.5 on 2020-04-23 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_auto_20200423_1204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
